### PR TITLE
fix(plugin-sass): additionalData function type

### PR DESCRIPTION
**Pull request by chenjiahan**
## Summary

Fix sass-loader's additionalData function type.

## Related Links

close https://github.com/web-infra-dev/rsbuild/issues/2582

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by CPatchane** [comment]
@chenjiahan According to https://github.com/webpack-contrib/sass-loader?tab=readme-ov-file#additionaldata, it can also be just a string.
With this change, it can only be a function.

**Comment by chenjiahan** [comment]
my mistake, I will fix it

**Comment by CPatchane** [comment]
FYI I suggested a PR to fix that on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70037

**Comment by chenjiahan** [comment]
Nice 👍🏻

**Comment by CPatchane** [comment]
> FYI I suggested a PR to fix that on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70037

It has been merged an release in the last version of `@types/sass-loader` 🎉

**Comment by chenjiahan** [comment]
Awesome, can you submit a PR to bump version and remove the override types? ❤️

**Comment by chenjiahan** [comment]
I think Rsbuild can still retain the type overrides, as `@types/sass-loader` depends on `webpack.LoaderContext` but Rsbuild should use `Rspack.LoaderContext`.

**Comment by CPatchane** [comment]
Thanks for the changes 🙌

**Pull request merged**
