### PR TITLE
feat(plugin-stylus): support `define` option

### LINKED ISSUE #3430: [Feature]: More Stylus options
### What problem does this feature solve?

Trying to migrate from webpack to rsbuild here but stuck:

Webpack's stylus loader has the `define` option:
https://webpack.js.org/loaders/stylus-loader/#stylusoptions

```ts
type stylusOptions =
  | {
      use: Array<string | Function>;
      include: Array<string>;
      import: Array<string>;
      define: Array; // <------------------------------ this one is missing
      includeCSS: false;
      resolveURL: boolean | Object;
      lineNumbers: boolean;
      hoistAtrules: boolean;
      compress: boolean;
    }
  | (loaderContext: LoaderContext) => Array<string>;
  ```

In my app, this enables to pass over some variables from the code to the styles which is extremely useful, such as media sizes.

If this could be added, that would be great. Thanks.

### What does the proposed API look like?

Presently, rsbuild has these types under @rsbuild/plugin-stylus/dist-types/index.d.ts:
```ts
type StylusOptions = {
    use?: string[];
    include?: string[];
    import?: string;
    resolveURL?: boolean;
    lineNumbers?: boolean;
    hoistAtrules?: boolean;
};
```

How about adding a new option named and typed the same way, `define`, allowing arrays? And in my code it would look like that:

```ts
define: [
  ["video-width", getVideoWidth(), true],
  ["video-height", getVideoHeight(), true],
],
```

### PR DESCRIPTION
**Pull request by shulaoda**
## Related Links

closes #3430 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by shulaoda** [comment]
Let me see if I can refine the any type to a more specific type.

**Review by chenjiahan — APPROVED** [review]
Nice 👍

**Comment by binarykitchen** [comment]
Nice, thanks. Maybe update documentation as well next time?

**Comment by shulaoda** [comment]
> Nice, thanks. Maybe update documentation as well next time?

Let me do it.

**Pull request merged**
