### PR TITLE
feat: automatically read tsconfig paths by `references`

### PR DESCRIPTION
**Pull request by chenjiahan**
## Summary

Automatically read tsconfig paths by `references`.

- `tsconfig.json`:

```json
{
  "references": [
    {
      "path": "./tsconfig.app.json"
    }
  ],
  "include": []
}
```

- `tsconfig.app.json`:

```json
{
  "compilerOptions": {
    "paths": {
      "@/common/*": ["./src/common/*"]
    }
  },
  "include": ["src"]
}
```

## Related Links

https://rspack.dev/config/resolve#resolvetsconfigreferences

## Checklist

- [x] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by SoonIter** [comment]
what if the user configures it like this

```json
{
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.node.json"
    }
  ],
  "include": []
}
```

- tsconfig.app.json

```json
{
  "compilerOptions": {
    "paths": {
      "@/common/*": ["./src/app/common/*"]
    }
  },
  "include": ["src"]
}
```

- "./tsconfig.node.json"

```json
{
  "compilerOptions": {
    "paths": {
      "@/common/*": ["./src/node/common/*"]
    }
  },
  "include": ["src"]
}
```

**Comment by SoonIter** [comment]
> what if the user configures it like this

😄 it will hit the first reference that hits `"include"`

**Comment by SoonIter** [comment]
how about adjusting our template like `create-vite`, 

```ts
├── rsbuild.config.ts
├── tsconfig.json
│ 
├── tsconfig.app.json
├── tsconfig.app.tsbuildinfo
│ 
├── tsconfig.node.json
└── tsconfig.node.tsbuildinfo
```

and adding `"build": "tsc -b && rsbuild build"` 😂 (or typecheck in `loadConfig`)

**Review by SoonIter — APPROVED** [review]

**Comment by chenjiahan** [comment]
> how about adjusting our template like create-vite,

We can, but I prefer to keep the template simple at this stage, unless something forces us to split the tsconfig files.

> adding "build": "tsc -b && rsbuild build"

I would prefer the opt-in `@rsbuild/plugin-type-check' instead of tsc..

**Pull request merged**
