### PR TITLE
fix(core): Disable buildin lightingcss when inject style

### PR DESCRIPTION
**Pull request by witsaint**
## Summary

For production builds, it is recommended to use the default behavior of Rsbuild, which extracts CSS into separate bundles to allow browsers to load CSS and JS assets in parallel.

## Related Links

[[Bug]: rsbuild injectStyles](https://github.com/web-infra-dev/rsbuild/issues/3247)

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Review by chenjiahan — COMMENTED** [review]
Can you explain why do we need to disable builtin lightingcss when using `injectStyles`?

**Comment by witsaint** [comment]
> Can you explain why do we need to disable builtin lightingcss when using `injectStyles`?

1: As described in our documentation, when we open injectStyles,If you need to enable this option in production mode, please note that the inlined CSS code will not go through Rsbuild's default CSS minimizer.

2: 
a： When I debugger Rsbuild，I found that there were five loaders before stylePostLoader
image

b：The latest loader is builtin lightingcss
image
The same is shown in rspack.config.web.mjs

c：I found that after using postcss with cssnano, source works fine，But by buildin lightingcss,Found a lot of \n
image

d: When I remove buildin lightingcss in loader, css compression is fine when injectStyles is turned on

**Comment by chenjiahan** [comment]
Get. I believe this fix is not the optimal solution as it prevents PostCSS and LightningCSS from working together.

We can solve this problem by simply adding a `minify` option to Rspack's lightningcss-loader and enanbling minify when `output.injectStyles` is used.

**Comment by chenjiahan** [comment]
Sorry, we should not change the order of lightningcss-loader and postcss-loader, this is an unexpected change.

Take Tailwind CSS as an example. Tailwind CSS it is a PostCSS plugin, it will generate some CSS code, then Lightning CSS will add vendor prefixes to those CSS properties. If we change the loader order, this will be broken.

**Comment by chenjiahan** [comment]
If we need to adjust the default loader behavior, it is best to first discuss the impact of doing so.

**Pull request closed without merging**
