### PR TITLE
feat(core): Remove the default exportOnlyLocals value from cssloader …

### PR DESCRIPTION
**Pull request by witsaint**
## Summary
Remove the default value of exportOnlyLocals when cssmodule is enabled，

When module is enabled, exportOnlyLocals is set to true by default，the exported value is incorrectly mounted

image

Therefore, exportOnlyLocals does not need a default value, leaving it up to the user to select

## Related Links
[[Bug]: SCSS files not loaded #1999](https://github.com/web-infra-dev/rsbuild/issues/1999)

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by chenjiahan** [comment]
Does https://github.com/web-infra-dev/rsbuild/issues/1999 related to `exportOnlyLocals`?

Rsbuild only sets `exportOnlyLocals` to `true` if `output.target` is not `'web'`, but #1999  does not seem to set `output.target.

**Comment by witsaint** [comment]
> Does #1999 related to `exportOnlyLocals`?
> 
> Rsbuild only sets `exportOnlyLocals` to `true` if `output.target` is not `'web'`, but #1999 does not seem to set `output.target`.

Yes ,I set `false`, compile fine
image

image

**Comment by chenjiahan** [comment]
Just run `DEBUG=rsbuild pnpm build` and you will find that Rsbuild does not set `exportOnlyLocals` by default.

image

**Comment by witsaint** [comment]
OK, It seems that the error report is not stable. There are other errors reported here. I will close MR First and then continue to see

**Comment by witsaint** [comment]
It seems that the error is not stable. There are other errors reported here. I will close MR First

**Pull request closed without merging**
