### PR TITLE
feat: OPTIONS request return success code

### PR DESCRIPTION
**Pull request by vtv6**
## Summary
Support returning success code in OPTIONS requests.
## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by chenjiahan** [comment]
Hi, can you provide more context for this change?

**Comment by vtv6** [comment]
> Hi, can you provide more context for this change?

**Comment by vtv6** [comment]
I'm integrating with Module Federation v2. Every time the shell app requests the `mf-manifest.json` file, an OPTIONS request is made to check CORS. However, the OPTIONS request always returns a 404 error, causing the CORS check to fail. Therefore, I referred to webpack-dev-server to create this MR

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
Thanks for the explanation, I have found the related PR from webpack-dev-server: https://github.com/webpack/webpack-dev-server/pull/4559

I will merge this PR and make some changes:

- Check-pick the commit to main branch, because we have no plan to release 0.x version for new features at present.
- Change the status code from `200` to `204`, because server does not response any data.
- Move the middleware to the last as a fallback.

**Pull request merged**
