### PR TITLE
fix: Trigger onFail only when the entire retry process has failed.

### PR DESCRIPTION
**Pull request by nanianlisao**
## Related Links

#2086 

## Checklist

- [ ] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by SoonIter** [comment]
I think I misunderstood the meaning of onFail. 
I thought it would be triggered every time when retry failed. I'll solve this error.😢

**Comment by SoonIter** [comment]
I have fixed this in #2201  and I'll add more test cases, thank you for the nice catch

**Comment by nanianlisao** [comment]
> I have fixed this in #2201 and I'll add more test cases, thank you for the nice catch

fine 👍, it would be best to also pass out the original error information during a retry. I believe this is also very necessary.

**Comment by chenjiahan** [comment]
Duplicated: https://github.com/web-infra-dev/rsbuild/pull/2201

Thanks ❤️

**Pull request closed without merging**
